sudo: false
dist: trusty

language: node_js

node_js:
  - 8.9.4

stages:
  - install
  - deploy

jobs:
  include:
    install:
      npm install
      npm install -g vsce
      npm install -g typescript
      tsc
      vsce package
      skip_cleanup: true
    deploy:
      - provider: script
        script: vsce publish -p $VSCODE
      - provider: script
        script: bash scripts/npm-deploy.sh $GITPASS
 
  
