sudo: false
dist: trusty

language: node_js

node_js:
  - 8.9.4

stages:
  - install
  - deploy

jobs:
  include:
    install:
      - npm install
      - npm install -g vsce typescript
      - tsc
      - vsce package
    deploy:
      - provider: script
        script: bash scripts/npm-deploy.sh $NPMTOKEN $NPMEMAIL $NPMUSER
        on:
          tags: true
          condition: tag =~ ^psl-lint && branch = master
      - provider: script
        script: vsce publish -p $VSCODE
        on:
          tags: true
          condition: tag =~ ^vscode-psl && branch = master
 
  
