stages:
  - name: install
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
  - name: compile
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
  - name: test:
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
  - name: package:
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
  - name: deploy:
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
    
language: node_js

node_js:
  - 8.9.4
  
install:
  - npm install
  - npm install -g vsce
  
compile:
  - npm run compile

test:
  - npm run test

package:
- vsce package

deploy:
- provider: script
  script: vsce publish -p $VSCODE
  
 -provider: script
  script: bash scripts/npm-deploy.sh
 
  
