sudo: false
dist: trusty

language: node_js

node_js:
  - 8.9.4

stages:
  - install
  - deploy

jobs:
  include:
    install:
      - npm install
      - npm install -g vsce typescript
      - tsc
      - vsce package
      - tsc src/alminio/main.ts
    deploy:
      - provider: script
        script: cp src/alminio/.npmrc.psl-lint $HOME/.npmrc && npm pack ./src/alminio | xargs npm publish
        on:
          branch: master
      - provider: script
        script: vsce publish -p $VSCODE
        on:
          tags: true
          condition: tag =~ ^vscode-psl && branch = master
 
  
