language: node_js

node_js:
  - 8.9.4
  
install:
  - npm install

script:
  - npm run compile
  - npm run test

before_deploy:
- npm install -g vsce;
- vsce package;

deploy:

- provider: script
  script: vsce publish -p $VSCODE
  skip_cleanup: true
  on:
    branch: master
    
- provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: $NPM
  on:
    branch: master
  
