sudo: false
dist: trusty

language: node_js

node_js:
  - 8.9.4

stages:
  - install
  - compile
  - package
  - deploy

jobs:
  include:
    install:
      npm install
      npm install -g vsce
      
    compile:
      - npm run compile
    package:
      - vsce package
    deploy:
      - provider: script
        script: vsce publish -p $VSCODE
      - provider: script
        script: bash scripts/npm-deploy.sh $GITPASS
 
  
