sudo: false
dist: trusty

language: node_js

node_js:
  - 8.9.4

stages:
  - install
  - deploy

jobs:
  include:
    install:
      - npm install
      - npm install -g vsce typescript vscode
      - tsc
      - vsce package
    deploy:
      - provider: script
        script: bash scripts/npm-deploy.sh $GITPASS
      - provider: script
        script: vsce publish -p $VSCODE
 
  
